services:
  - type: web
    name: laudspeaker
    env: docker
    dockerCommand: docker-compose -f docker-compose.prod.yml up
    envVars:
      # Database Configuration
      - key: DATABASE_URL
        value: postgresql://astrazen_user:YlENu30fCsf3qpjzKggLBm0EWJb6LbMS@dpg-otc292ogph6c73aabl50-a/astrazen
      - key: DATABASE_SSL
        value: true

      # Redis Configuration
      - key: REDIS_HOST
        value: redis-12988.c283.us-east-1-4.ec2.redns.redis-cloud.com
      - key: REDIS_PORT
        value: 12988
      - key: REDIS_PASSWORD
        value: cYRKTgLTXTiI1asnwQgsgISDy3ctHm8R
      - key: REDIS_USERNAME
        value: default

      # Clickhouse Configuration
      - key: CLICKHOUSE_HOST
        value: okai3ae0ad.ap-south-1.aws.clickhouse.cloud
      - key: CLICKHOUSE_PORT
        value: 8443
      - key: CLICKHOUSE_USER
        value: default
      - key: CLICKHOUSE_PASSWORD
        value: fFc.5FoDUOZZQ
      - key: CLICKHOUSE_DB
        value: default

      # MongoDB Configuration
      - key: MONGODB_URI
        value: mongodb+srv://2f1YzyuwkogQRbWa:2f1YzyuwkogQRbWaaastrazen.q4mjj.mongodb.net/?authSource=admin

      # Kafka Configuration
      - key: KAFKA_BROKERS
        value: kafka1:20092
      - key: KAFKA_CLIENT_ID
        value: laudspeaker-client
      - key: KAFKA_GROUP_ID
        value: laudspeaker-consumer-group

      # Application Configuration
      - key: NODE_ENV
        value: production
      - key: JOURNEY_ONBOARDING
        value: true
      - key: SYNCHRONIZE
        value: true
      - key: PORT
        value: 3001
      
      # Frontend Configuration
      - key: REACT_APP_API_BASE_URL
        sync: false
      - key: REACT_APP_WS_BASE_URL
        sync: false

    healthCheckPath: /health
    buildCommand: docker-compose -f docker-compose.prod.yml build
    startCommand: docker-compose -f docker-compose.prod.yml up -d

databases:
  - name: laudspeaker-db
